sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yuantu123
  alioss:
    #参数乱敲
    bucket-name: 3443554
    access-key-secret: 3543655
    endpoint: 53545
    access-key-id: 656465
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    database: 0

  wechat:
    appid: 321432432
    secret: 5435343
    mchid: 2432432
    mchSerialNo: 323243
    privateKeyFilePath: 4r43
    apiV3Key: 3243
    weChatPayCertFilePath: 3454543
    notifyUrl: 232321
    refundNotifyUrl: 2131231